version: '3.5'
services:
  web:
      container_name: react-docker
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        - '.:/usr/src/app'
        - '/usr/src/app/node_modules'
      ports:
        - '8000:8000'